### ISSUE TITLE
can_grow remains False when reusing complete_db_medium results with new medium

### ISSUE THREAD

**Issue by lauraminkova** [micom-dev/media#1]
Hi there, 

I've recently begun using MICOM for microbiome data (can't thank you enough for the clear documentation!), and have been looking into using different diets from the VMH site. I tried rerunning the notebook for the high fat, low carb diet but came across something unusual. I recreated the agora database using the manifest table that we get after complete_db_medium, and saved both the database and the new medium vmh_high_fat_low_carb_agora.qza. However, when I re-ran check_db_medium with the new database and vmh_high_fat_low_carb_agora.qza I got all False for the can_grow column. Is this to be expected, or am I missing something? Any help would be appreciated, and please let me know if anything I've mentioned has been unclear.

Thanks, 
Laura

**Comment by cdiener** [comment]
Oh yeah, good catch. There was a bug in renaming the IDs for the final medium that garbled some of the names for essential metabolites (like Magnesium) and resulted in infeasible growth media. I will push a fix in the afternoon. Thanks for spotting this. This only affected check_medium though (only affected the global_id column which is not used by other MICOM methods). The media will still work fine in MICOM community models.

**Comment by cdiener** [comment]
Now fixed in v1.1.1. Thanks!

**Comment by lauraminkova** [comment]
Thank you so much!
